### ISSUE TITLE
Agregar tags sociales

### ISSUE THREAD

**Issue by edittler** [lugfi/lugfi.github.io#10]
Agregar los tags de [Open Graph](http://ogp.me/) (para Facebook) y [Twitter Cards](https://dev.twitter.com/cards/markup).
De esta manera se mostraría información más relevante al momento de compartir los artículos en las redes sociales.

**Comment by colltoaction** [comment]
@mlafroce tenía ganas de hacerlo

**Comment by edittler** [comment]
Se puede usar el [debugger de Facebook](https://developers.facebook.com/tools/debug/sharing/) y el [validador de Twitter](https://cards-dev.twitter.com/validator) para verificar que los tags sean interpretados correctamente y la vista previa se muestre como se desea. Yo estoy conforme con el resultado :grinning:
