### ISSUE TITLE
Agregar comentarios por post

### ISSUE THREAD

**Issue by mlafroce** [lugfi/lugfi.github.io#12]
Los dos sistemas de comentarios más populares son los de Facebook y Disqus
¿Se va a utilizar alguno de ellos?
Para facebook hace falta una cuenta developer, para Disqus seguramente hay alguna funcionalidad de administración.
O mejor aun (al menos, mejor que Disqus) podríamos tener otro sistema open source hosteado por nosotros, como [Isso](https://github.com/posativ/isso)

**Comment by AlexDaciuk** [comment]
Estaria bueno, preferiria no usar Facebook igual, Disqus lo uso en mi blog y no tengo problemas

Isso se podria usar aca? o hay que hostearlo en otro lado? 

Lo comodo de disqus, es que metes un poco de codigo y listo

**Comment by edittler** [comment]
Facebook claramente no.
Disqus no solo no es open source si no que te obliga a tener una cuenta de Disqus, perdiendo en privacidad, que es una de las cosas que se valora en el ámbito de software libre.
[Isso](https://github.com/posativ/isso) parece una buena alternativa. Dado que se requiere Python, habría que analizar como [instalarlo](https://posativ.org/isso/docs/install/).

**Comment by edittler** [comment]
Por si no lo notaron, se usa como sistema de comentarios las respuesta a una discusión que se genera automáticamente en la [sección "Publicaciones Web" de nuestro foro](https://foro.lug.fi.uba.ar/c/publicaciones-web). Obviamente, para poder comentar hay que tener cuenta en el foro (de hecho se responde dentro del foro y no en el sitio de LUGFI).

**Comment by AlexDaciuk** [comment]
Entonces se podría cerrar este issue?

Basicament ya agregamos la opcion de comentar

**Comment by colltoaction** [comment]
Me gusta la solución, es sencilla y fomenta la participación en el foro. Cierro esto.
