### ISSUE TITLE
Los iconos de contacto del footer no se ven en Chrome ni Firefox de escritorio

### ISSUE THREAD

**Issue by AlexDaciuk** [lugfi/lugfi.github.io#28]
Los iconos de contacto no se ven en navegadores de escritorios (adjunto screenshot) pero si en navegadores mobiles, no tendria que aparecer en todos?

Firefox
![lugfi](https://cloud.githubusercontent.com/assets/2780694/17707133/65625a50-63b5-11e6-8fc1-0e242bc16566.png)

Chromium / Chrome
![chrome](https://cloud.githubusercontent.com/assets/2780694/17707165/7aac3052-63b5-11e6-9043-35d12e92b24f.png)

Chrome Android
![screenshot_20160816-132509](https://cloud.githubusercontent.com/assets/2780694/17707171/81a277f4-63b5-11e6-883c-a0ff1207a3e3.png)

**Comment by edittler** [comment]
Si, debería aparecer en todas las plataformas. En un rato reviso que es.

**Comment by edittler** [comment]
En mi PC los veo a los íconos.

¿Podés abrir el inspector web y verificar si la consola muestra algún error?

Una de las razones por la que puede que no ande, es que no cargue el archivo `font-awesome.min.css`.

**Comment by AlexDaciuk** [comment]
Aunque en el source de la pagina aparezca el codigo correspondiende a <ul class="social-media" , no aparecen los iconos

Si, el archivo "font-awesome.min.css" se carga sin problemas

Te funciona? que navegador?

**Comment by AlexDaciuk** [comment]
Ya me di cuenta que es, el filtro "Anti-ThirdpartySocial" de uBlock Origin me bloquea el link de facebook, por lo tanto todo el ul que contiene los links sociales, mala mia, cierro el issue
