### ISSUE TITLE
Agregar licencia libre de documentos  al repositorio y al footer de las entradas

### ISSUE THREAD

**Issue by AlexDaciuk** [lugfi/lugfi.github.io#30]
Viendo que el repo de la pagina ni la pagina misma tiene algun indicio de licencia, pensaba que tendriamos que poner alguna de las Creative Commons

Como licencia del repo y agregar una imagen en el footer de cada entrada de la pagina

Les parece Creative Commons, Attribution, Share Alike y Non Commercial?

**Comment by edittler** [comment]
Totalmente de acuerdo! Yo me ofrezco para poner los iconos de CC en el footer.

**Comment by AlexDaciuk** [comment]
Copado, ahora nos tenemos que poner deacuerdo sobre cual de todas usar

**Comment by edittler** [comment]
Este es un buen sitio donde en base a sólo 2 pregunta ya te dice que licencia es la que corresponde.
https://creativecommons.org/choose/?lang=es_AR

La que me parece más adecuada es Atribución-CompartirIgual (by-sa), la misma que usa Wikipedia para todo su contenido.
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by AlexDaciuk** [comment]
Y el no comercial?

**Comment by colltoaction** [comment]
Solo para revivir esto... yo confío en la que elija cualquiera

**Comment by AlexDaciuk** [comment]
Bueno, vamos por Atribucion-CompartirIgual (by-sa)

Creo que el icono normal esta bien, aunque me parece un poco chico en 88x31, baje el SVG y lo deje en 150x53, creo que esta bien, de ultima se cambia 

![Imagen Licencia](https://cloud.githubusercontent.com/assets/2780694/18657723/3e797c82-7ed3-11e6-849f-6ec8165d9acc.png)

Creeria que podes empezar cuando puedas @ezeperez26

**Comment by edittler** [comment]
Si, yo me encargo. El finde lo hago. En qué posición lo ponemos? Debajo de los iconos de redes sociales?

**Comment by AlexDaciuk** [comment]
Si, creo que centrado bajo los iconos de redes sociales esta perfecto

**Comment by edittler** [comment]
Con los cambios aplicados en #32 ya estaría resuelto.
