### ISSUE TITLE
Información sobre el foro de LUGFI

### ISSUE THREAD

**Issue by edittler** [lugfi/lugfi.github.io#38]
¿Donde agregamos links al foro? ¿En el footer junto con el resto de los íconos? ¿En la barra de navegación?

Por otro lado, ¿algún post de "bienvenida" al foro?

**Comment by AlexDaciuk** [comment]
Creeria que en el footer, junto a todo lo otro

Nope, no hay post de "Bienvenida" y creeria que vamos a quedar como medio tontos si creamos uno ahora no?

**Comment by edittler** [comment]
En la mayoría de los sitios lo veo en la barra de navegación.
Incluso como está siempre visible tendría más llegada.

Veremos que opinan otros miembros de LUGFI

**Comment by AlexDaciuk** [comment]
Para eso, pongamos todo en la barra de navegación, ya que tiene mas visibilidad, no?

**Comment by edittler** [comment]
Tampoco la pavada. O sea, particularmente el foro me parece que sí debería ir en la barra de navegación por que considero que es la herramienta en la que se debe centrar LUGFI. El resto (Facebook, Twitter, Telegram) no. Sepamos medir las prioridades y no tirar esas frases sin sentido que no realizan aporte alguno a la discusión.

Paso algunos ejemplos donde el foro tiene particular relevancia:
- http://www.xda-developers.com/
- http://www.discourse.org/ (botón "Meta")

**Comment by AlexDaciuk** [comment]
Ya que el link al foro ya esta en la barra de navegacion, cierro el issue
