### ISSUE TITLE
Migrar contenido del viejo lugfi

### ISSUE THREAD

**Issue by colltoaction** [lugfi/lugfi.github.io#4]
Hay contenido que podríamos reutilizar. Por ejemplo, los "Acerca De" serían fáciles.

http://web.archive.org/web/20091229002228/http://www.lug.fi.uba.ar/

**Comment by edittler** [comment]
Buena idea.
Los contenidos migrables podrían ser:
- Acerca de
- Historia (lo renombraría a "Reseña histórica")
- Contacto (por ahora el grupo de Facebook y Telegram si ya está activo)
- Programas para Ingeniería ("Software para Ingeniería")
- Links/Otros LUGs

Me gusta la idea de que idea de que cada uno haga un branch o fork y luego con pull request se someta a una aprobación de varios usuarios. Habría que definir el criterio de aprobación.

**Comment by colltoaction** [comment]
El archive está caído de nuevo... alguien habrá guardado el contenido?

**Comment by edittler** [comment]
Ahora está el sitio viejo en [lugfi.github.io/lugfi-classic](https://lugfi.github.io/lugfi-classic/).
Podemos ver su contenido tranquilos y sin miedo de que se caiga de nuevo 😃

**Comment by AlexDaciuk** [comment]
Hace falta algo mas a esto? o porque no se cerro el issue?

**Comment by colltoaction** [comment]
Siempre se puede mejorar... pero es un laburo chino. Cierro, pero si alguien quiere seguir con la arqueología es bienvenido a armar un PR.
