### ISSUE TITLE
Aplicar algún tema o estilos

### ISSUE THREAD

**Issue by colltoaction** [lugfi/lugfi.github.io#5]
@ezeperez26 recomendó https://github.com/jekyll/jekyll/wiki/Themes

**Comment by colltoaction** [comment]
http://daktilo.github.io/ ?

**Comment by edittler** [comment]
Está bueno. A la demo le falta mostrar como sería tipo blog.

A mi me gustaron estos, que tiene una barra superior para facilitar la navegación:
- http://blackrockdigital.github.io/startbootstrap-clean-blog-jekyll/ (la barra se oculta y aparece automáticamente)
- http://pavelmakhov.com/jekyll-clean-dark/ (un estilo muy nerd, acorde a la temática del grupo 😁 )
- http://deanattali.com/beautiful-jekyll/ (la barra se reduce al desplazarse y posee submenu)

A pesar de que algunos temas indican que soportan pugins de Jekyll, en GitHub Pages solo se permiten ciertos plugins, como lo indica su [documentación](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/).

El resto del team recibe notificaciones de estos issues?

**Comment by colltoaction** [comment]
Ni idea

**Comment by AlexDaciuk** [comment]
Estuve mirando los temas que hay para jekyll, estos 2 me gustaron bastante

https://github.com/mattvh/solar-theme-jekyll  (demo : http://mattvh.github.io/solar-theme-jekyll/)

https://github.com/railsr/autm-rb (demo: http://railsr.github.io/autm-rb/blog/) 

mas que nada porque no son puro blanco y no te queman la vista

no se, ustedes fijense

**Comment by edittler** [comment]
Según la [minuta 0](https://lugfi.github.io/2016/07/21/minuta-0.html)

> Se propuso usar el template utilizado por @mlafroce, [Clean Dark theme](http://pavelmakhov.com/jekyll-clean-dark/)

No estuve presente en esa reunión, pero pensé que ya estaba resuelto el tema jaja

**Comment by colltoaction** [comment]
Neh, era una idea nomás :p

**Comment by AlexDaciuk** [comment]
No se, como no pusieron el tema, pense que quedo en la nada, digan que le parecen los otros temas y vemos cual ponemos, el Solar Theme lo tuve un tiempo en mi blog y era bastante lindo, aunque tenga una paleta rara de colores

**Comment by edittler** [comment]
La paleta de colores del Solar Theme no se destaca por ser linda jaja
Yo había propuesto Dark Theme y en una reunion parece que varios habían ido a esa opción. Podríamos decantar por eso y nos ponemos manos a la obra.

**Comment by AlexDaciuk** [comment]
A mi no me molesta ninguno que esta propuesto en este Issue, no quiero meter mano porque nunca toque jekyll, el que quiera, que ponga un tema, de ultima si a una mayoria no le gusta, se cambia, la idea es que cambien el default almenos

**Comment by edittler** [comment]
Ya estoy trabajando en el cambio de estilo a Dark Theme. A la tarde van a tener algo publicado 😄

**Comment by edittler** [comment]
En el PR #18 están todos los cambios para que tenga el estilo Dark Theme.
