### ISSUE TITLE
Permisos de escritura

### ISSUE THREAD

**Issue by colltoaction** [lugfi/lugfi.github.io#6]
@AlexDaciuk todos tienen permisos de lectura a este repo por default, y nadie puede escribir. Cómo te parece hacer esto? Querés dar permisos de escritura por defecto?

**Comment by edittler** [comment]
Lo que tiene de bueno las organizaciones de GitHub es que se pueden hacer teams, permitiendo que los miembros puedan tener acceso a ciertos repositorios. Es decir, granular el acceso a los repositorios. La [doc oficial](https://help.github.com/articles/setting-up-teams/) explica mejor esto.

Recién hice el team @LUGFi/web para administrar este repo y te puse como admin @tinchou. Tendrías que agregar este repositorio al team y todos los que están ahí tendrían acceso (como vos lo creaste sos el único que podés hacerlo, creo).

Seguramente me desvíe del tema, pero una organización con un owner no es muy seguro en el sentido de que un día falta ese owner y muere la organización.

**Comment by colltoaction** [comment]
Listo el grupo en este repo. @AlexDaciuk fijate si querés hacer a alguien más admin como dice Eze! Yo no tengo problema,. E encanta administrar cosas jaja
